name: Neon
author: ICities
version: '1.9'
api-version: '1.14'
depend: []
softdepend: []
main: com.islandstudio.neon.MainCore
description: Server Tools.

commands:
  neon:
    usage: /<command>
    description: Command prefix.

  ldl:
    usage: /<command>
    description: Internal command.

  plugin:
    description: Null.

  plugins:
    description: Null.

  pl:
    description: Null.

  ?:
    description: Null

  help:
    description: Null.