name: Neon
author: ICities
version: '1.10.1-rc_3'
api-version: '1.17'
depend: []
softdepend: []
main: com.islandstudio.neon.Neon
description: Plugin for Spigot/Paper MC server

commands:
  neon:
    usage: /<command>
    description: Command prefix.